version: "3"
services:

  app:
    image: danstreeter/speedtest-influx-logger:0.0.3
    environment:
      - NODE_NAME=development
      - INFLUX_HOST=influx
      - INFLUX_PORT=8086
      - INFLUX_USER=CHANGEME
      - INFLUX_PASS=CHANGEME
      - INFLUX_DB=internetspeed
      - TEST_FREQUENCY=10
    restart: unless-stopped

  influx:
    image: influxdb:1.7
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=internetspeed
      - INFLUXDB_ADMIN_USER=CHANGEME
      - INFLUXDB_ADMIN_USER_PASSWORD=CHANGEME
      - INFLUXDB_USER=CHANGEME
      - INFLUXDB_USER_PASSWORD=CHANGEME
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data: